[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/request-mangment"

[[plugins]]
  package = "@netlify/angular-runtime"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
